### ISSUE TITLE
Can you add a pandoc conversion to DOCX for each of the .rst files please.  

### ISSUE THREAD

**Issue by c19witness** [dracos/uk-covid19-inquiry#1]
Check those back into Git even though they are binary..

That'd be great :)

**Comment by dracos** [comment]
Could you provide some more details? How would this be useful? Whilst I am happy to look into things, or at pull requests to add things, I don't really want to add things that could increase the maintenance burden.

**Comment by c19witness** [comment]
Having a DOCX version of each transcript allows groups to take the doc into the GoogleDocs system privately, then debate among each other using the built-in comment system.

- were all the questions asked that needed to be asked for each witness
- were the answer given sufficient or contradictory to evidence given or known facts elsewhere.

Then that group could publish their rolled up commentary. Full disclosure - the group I am a fan of is "covid-is-airborne and we should have called it as such at the beginning"

**Comment by dracos** [comment]
I've just gone to https://ukcovid19inquiry.dracos.co.uk/module-2/2023-10-13/ , selected all the text from the "Transcript of..." heading to "Monday, 16 October 2023)" at the end, copied, and pasted into a blank Google Document, and it maintained the formatting and heading structure fine: https://docs.google.com/document/d/1BdirsZpS6fbhU6GuWlJWnxxqH7AEv6OugGp4miebQ5Y/edit#heading=h.4h5aaqr28e74 - Given that, I'm not sure I need to create special other versions of the transcript.

**Comment by c19witness** [comment]
OK, no probs.
