### ISSUE TITLE
List core participants on the home page, maybe?

### ISSUE THREAD

**Issue by c19witness** [dracos/uk-covid19-inquiry#2]
Any chance of making a list of the groups (Core Participants) that are represented at the inquiry?

https://covid19.public-inquiry.uk/documents/list-of-module-1-core-participants/
https://covid19.public-inquiry.uk/documents/list-of-module-2-core-participants/
https://covid19.public-inquiry.uk/documents/list-of-module-3-core-participants/
https://covid19.public-inquiry.uk/documents/list-of-module-4-core-participants/

These back into HTML.  If not on the home page then linked to from it?

**Comment by dracos** [comment]
If you'd like to submit a pull request adding that information as a page or pages on the site, sure, happy to include that. Most straightforward is probably to add a single `core-participants.rst` file containing all the information in reStructuredText format (documentation at https://docutils.sourceforge.io/rst.html ).

**Comment by c19witness** [comment]
[core_participant-html-fileszip.zip](https://github.com/dracos/uk-covid19-inquiry/files/13318092/core_participant-html-fileszip.zip)
those PDFs converted to HTML.  Should I go on to do one more conversion to .rst from there.  Multi-line table cells is making the conversion tools choke, but I could experiment some more?

Ugh - even the HTML is horrible. This is a job for GPT or UpWork :(

**Comment by c19witness** [comment]
Workflow was copy/paste from PDF as view in Safari, to a text file, then add RST table-fu prefix:

[cp.rst.zip](https://github.com/dracos/uk-covid19-inquiry/files/13319078/cp.rst.zip)

There's display glitches - widths of columns are percentages, but it seems to go waay wider than the container when presented in the gen'd site.

**Comment by dracos** [comment]
Thanks! I've added that at https://ukcovid19inquiry.dracos.co.uk/core-participants/ in 0e0bb2ac3783c5d9b9b98f2fb049f1698940c43e (with title so it parsed and a line of CSS to stop it going wider).

**Comment by c19witness** [comment]
Thanks. Looking at it some more .. if I made a PR that de-duplicated the rows - showing which modules each group is recognize for, and dropped the date, would that be OK?

![image](https://github.com/dracos/uk-covid19-inquiry/assets/125606732/21b19fa9-66f7-45eb-b0de-16ac52351b14)

**Comment by dracos** [comment]
Sure!

**Comment by c19witness** [comment]
Here it is https://github.com/dracos/uk-covid19-inquiry/pull/3
